version: "3.7"
services:
    flask:
        container_name: flask-server-container
        hostname: flask-server
        build:
            context: ../../
            dockerfile: ./deployment/development/Dockerfile
        working_dir: /usr/local/
        ports:
            - "5000:5000"
        volumes:
            - type: bind
              source: ../../app/
              target: /usr/local/application/
        command: ["gunicorn", "application.manage:app", "-c", "application/config/gunicorn_setting.py"]
        restart: "no"
